name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate
      run: cmake . -B.build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build .build/

    - name: Test
      run: ctest .build/